Create and Update Blazor Wasm App Registrations
dotnet/Scaffolding pull request #1793
Opened 2022-01-11 20:23 UTC by zahalzel

2022-01-11 20:24 UTC, zahalzel commented on src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
> +            Debugger.Launch();
Will remove shortly

2022-01-12 21:18 UTC, deepchoudhery requested changes
A step-by-step description of the Blazor WASM flow (pertaining to the implementation) would be great for the PR description as well.

2022-01-12 21:18 UTC, deepchoudhery commented on src/MSIdentityScaffolding/Microsoft.DotNet.MSIdentity/MicrosoftIdentityPlatform/MicrosoftIdentityPlatformApplicationManager.cs
> +        private Application? UpdateApplication(Application existingApplication, ProvisioningToolOptions toolOptions, bool isBlazorWasm = false)
Would it be possible to update both `UpdateApplication` method's summaries with a description of the flow of changes. It's quite confusing to read through with very basic comments. Not sure why we are calling certain things.

2022-01-13 19:08 UTC, deepchoudhery approved these changes
LGTM

2022-01-13 19:26 UTC, merged